# Generated by Django 4.0.1 on 2022-02-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0010_alter_userdetails_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='email_id',
        ),
    ]
