# Generated by Django 4.0.1 on 2022-02-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0012_remove_user_email_id_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='plan',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
