# Generated by Django 4.0.1 on 2022-02-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_plan_remove_user_bio_remove_user_name_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='created_year',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
