# Generated by Django 4.0.1 on 2022-02-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_remove_userdetails_name_alter_userdetails_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['-released']},
        ),
        migrations.RemoveField(
            model_name='production',
            name='created_year',
        ),
        migrations.RemoveField(
            model_name='show',
            name='created',
        ),
        migrations.AddField(
            model_name='production',
            name='created',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='released',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='name',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='phno',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
