# Generated by Django 4.0.1 on 2022-02-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0006_alter_user_email_alter_userdetails_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30, null=True, unique=True),
        ),
    ]
