# Generated by Django 4.0.1 on 2022-02-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
