# Generated by Django 4.0.1 on 2022-02-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
